### ISSUE TITLE
Package not compatible with atom latest update 1.31.2

### ISSUE THREAD

**Issue by hsuk-404** [mgrenier/remote-ftp#1213]
I have updated my atom to 1.31.2 and it gives you an error while you try to connect. 

```
Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string
/Users/kush/.atom/packages/remote-ftp/lib/client.js:221
Hide Stack Trace
Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/Users/kush/.atom/packages/remote-ftp/lib/client.js:221:45)
    at HTMLAnchorElement.<anonymous> (/Users/kush/.atom/packages/remote-ftp/lib/views/tree-view.js:154:30)
    at HTMLDivElement.dispatch (/Users/kush/.atom/packages/remote-ftp/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Users/kush/.atom/packages/remote-ftp/node_modules/jquery/dist/jquery.js:4121:28)
```

I was able to connect when I have my .ftpconfig file open but while you try to open remote files it will give you:

```
Uncaught TypeError: path must be a string or Buffer
fs.js:636
Hide Stack Trace
TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:636:11)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:200:20)
    at tryStat (/Users/kush/.atom/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:1072:11)
    at SFTPStream._transform (/Users/kush/.atom/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:501:15)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/Users/kush/.atom/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
```

**Comment by TihomirS** [comment]
same here .. atom 1.32.2 x64 ..
Error: Login authentication failed - on normal FTP 
other FTP client's work fine .. I'm tried with a different password (with/without special chars)

**Comment by icetee** [comment]
Tree-view has changed, I've fixed a query.

**Comment by TihomirS** [comment]
atom 1.32.2 x64 - remote-ftp 2.2.1 - WORKING :)
after an update, I get the same error but when delete and create new config file it starts working :)
thanks,
T.
