### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'F:/Programming\floshox_website_06-03-20\...

### ISSUE THREAD

**Issue by florian-cassagne** [mgrenier/remote-ftp#1321]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'F:\Programming\floshox_website_06-03-20\public_html\.ftpconfig'

```
At fs.js:115

Error: ENOENT: no such file or directory, stat 'F:\Programming\floshox_website_06-03-20\public_html\.ftpconfig'
    at statSync (fs.js:829:3)
    at Object.fs.statSync (ELECTRON_ASAR.js:284:27)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:696:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:153:9
    at final (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:513:11)
    at Socket.ondone (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:488:7)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -1:52.3.0 tree-view:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -1:48.1.0 core:confirm (input.hidden-input)
     -1:28 core:paste (input.hidden-input)
     -1:26.6.0 core:save (input.hidden-input)
  2x -1:03.5.0 core:paste (input.hidden-input)
     -0:47.7.0 core:backspace (input.hidden-input)
  2x -0:46.7.0 core:save (input.hidden-input)
  6x -0:39.3.0 remote-ftp:connect (input.hidden-input)
```

### Non-Core Packages

```
ide-cpp 0.1.0 
ide-css 0.3.3 
ide-html 0.6.0 
ide-java 0.9.0 
ide-php 0.7.18 
remote-ftp 2.2.4 
teletype 0.13.4 
```

**Comment by martincysiam** [comment]
Fix can be found here: #1374
