### ISSUE TITLE
Installing remote-ftp 2.2.4 in atom 1.42.0 Failed

### ISSUE THREAD

**Issue by riz4l** [mgrenier/remote-ftp#1322]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Fahrizal\\AppData\\Local\\atom\\app-1.42.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Fahrizal\\AppData\\Local\\atom\\app-1.42.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\Fahrizal\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\Fahrizal\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball',
1 verbose cli   '--target=4.2.7',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v10.2.1
4 verbose npm-session c0c839d51b0bc586
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball 4879ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball fetched in 4981ms
9 timing stage:loadCurrentTree Completed in 6808ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule remote-ftp@2.2.4 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/ssh2-streams 1682ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/ssh-config 1689ms (from cache)
19 silly pacote range manifest for ssh-config@^3.0.0 fetched in 1696ms
20 silly resolveWithNewModule ssh-config@3.0.1 checking installable status
21 http fetch GET 200 https://registry.npmjs.org/ssh2-streams/-/ssh2-streams-0.4.9.tgz 15ms (from cache)
22 silly fetchPackageMetaData error for ssh2-streams@^0.4.8 zlib: unexpected end of file
23 http fetch GET 304 https://registry.npmjs.org/event-kit 1741ms (from cache)
24 silly pacote range manifest for event-kit@^2.5.3 fetched in 1747ms
25 silly resolveWithNewModule event-kit@2.5.3 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/fs-plus 2193ms (from cache)
27 silly pacote range manifest for fs-plus@^3.1.1 fetched in 2200ms
28 silly resolveWithNewModule fs-plus@3.1.1 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/ssh2 2198ms (from cache)
30 silly pacote range manifest for ssh2@^0.8.7 fetched in 2207ms
31 silly resolveWithNewModule ssh2@0.8.8 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/atom-space-pen-views 3084ms (from cache)
33 silly pacote range manifest for atom-space-pen-views@^2.2.0 fetched in 3091ms
34 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/strip-json-comments 3126ms (from cache)
36 http fetch GET 304 https://registry.npmjs.org/ignore 3136ms (from cache)
37 silly pacote range manifest for strip-json-comments@^2.0.1 fetched in 3132ms
38 silly resolveWithNewModule strip-json-comments@2.0.1 checking installable status
39 silly pacote range manifest for ignore@^4.0.6 fetched in 3142ms
40 silly resolveWithNewModule ignore@4.0.6 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/@icetee%2fftp 3898ms (from cache)
42 silly pacote range manifest for @icetee/ftp@^1.0.5 fetched in 3904ms
43 silly resolveWithNewModule @icetee/ftp@1.0.5 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/cson-parser 3956ms (from cache)
45 silly pacote range manifest for cson-parser@^3.0.0 fetched in 3961ms
46 silly resolveWithNewModule cson-parser@3.0.0 checking installable status
47 timing stage:rollbackFailedOptional Completed in 0ms
48 timing stage:runTopLevelLifecycles Completed in 10784ms
49 silly saveTree apm-install-dir-120215-10556-1f24q9j.gdj6j
49 silly saveTree `-- remote-ftp@2.2.4
49 silly saveTree   +-- @icetee/ftp@1.0.5
49 silly saveTree   +-- atom-space-pen-views@2.2.0
49 silly saveTree   +-- cson-parser@3.0.0
49 silly saveTree   +-- event-kit@2.5.3
49 silly saveTree   +-- fs-plus@3.1.1
49 silly saveTree   +-- ignore@4.0.6
49 silly saveTree   +-- ssh-config@3.0.1
49 silly saveTree   +-- ssh2@0.8.8
49 silly saveTree   `-- strip-json-comments@2.0.1
50 verbose stack ZlibError: zlib: unexpected end of file
50 verbose stack     at Zlib.(anonymous function).onerror (C:\Users\Fahrizal\AppData\Local\atom\app-1.42.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:131:21)
50 verbose stack     at Unzip.write (C:\Users\Fahrizal\AppData\Local\atom\app-1.42.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:255:31)
50 verbose stack     at Unzip.flush (C:\Users\Fahrizal\AppData\Local\atom\app-1.42.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:222:10)
50 verbose stack     at Unzip.end (C:\Users\Fahrizal\AppData\Local\atom\app-1.42.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:229:10)
50 verbose stack     at Object.end (C:\Users\Fahrizal\AppData\Local\atom\app-1.42.0\resources\app\apm\node_modules\npm\node_modules\tar\lib\parse.js:415:21)
50 verbose stack     at PassThrough.onend (_stream_readable.js:634:10)
50 verbose stack     at Object.onceWrapper (events.js:273:13)
50 verbose stack     at PassThrough.emit (events.js:187:15)
50 verbose stack     at endReadableNT (_stream_readable.js:1090:12)
50 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
51 verbose cwd C:\Users\Fahrizal\AppData\Local\Temp\apm-install-dir-120215-10556-1f24q9j.gdj6j
52 verbose Windows_NT 10.0.18363
53 verbose argv "C:\\Users\\Fahrizal\\AppData\\Local\\atom\\app-1.42.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Fahrizal\\AppData\\Local\\atom\\app-1.42.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Fahrizal\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Fahrizal\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
54 verbose node v10.2.1
55 verbose npm  v6.2.0
56 error code Z_BUF_ERROR
57 error errno -5
58 error zlib: unexpected end of file
59 verbose exit [ -5, true ]

**Comment by riz4l** [comment]
please help, I really need, to fix this, i installed in window 10 64bit
