### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Documents\fhgr\web\im2\infected\.ftpco...

### ISSUE THREAD

**Issue by Takoyaki-cypto** [mgrenier/remote-ftp#1328]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: DPV-MMP19C2
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\danil\Documents\fhgr\web\im2\infected\.ftpconfig'

```
At fs.js:115

Error: ENOENT: no such file or directory, stat 'C:\Users\danil\Documents\fhgr\web\im2\infected\.ftpconfig'
    at statSync (fs.js:829:3)
    at Object.fs.statSync (ELECTRON_ASAR.js:284:27)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:750:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:638:9)
    at /packages/remote-ftp/lib/connectors/ftp.js:665:16
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1088:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at Parser.emit (events.js:187:15)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
     -5:01.2.0 core:save (input.hidden-input)
     -4:20.4.0 tree-view:remove (span.name.icon.html5-icon.medium-orange)
     -4:01.9.0 core:save (div.tool-panel.tree-view)
     -3:56.1.0 atom-live-server:startServer (div.tool-panel.tree-view)
     -2:46 remote-ftp:connect (div.tool-panel.tree-view)
     -2:20 tree-view:remove (div.tool-panel.tree-view)
     -2:04.9.0 remote-ftp:connect (div.tool-panel.tree-view)
     -1:24.5.0 intentions:highlight (input.hidden-input)
     -1:24.3.0 core:save (input.hidden-input)
     -1:15.8.0 remote-ftp:connect (input.hidden-input)
  2x -1:03.4.0 core:move-left (input.hidden-input)
 12x -0:54.6.0 core:delete (input.hidden-input)
     -0:52 intentions:highlight (input.hidden-input)
     -0:51.7.0 core:save (input.hidden-input)
  2x -0:30.4.0 remote-ftp:toggle (div.tool-panel.tree-view)
     -0:15.7.0 remote-ftp:connect (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
atom-python-run 0.9.7 
atom-runner 2.7.1 
atom-ternjs 0.20.0 
autocomplete-project-paths 2.2.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
es6-javascript 1.0.0 
file-icons 2.1.41 
hyperclick 0.1.5 
intentions 1.1.5 
jquery-snippets 11.0.0 
kite 0.184.0 
linter 2.3.1 
linter-jscs 4.2.4 
linter-jshint 3.1.19 
linter-ui-default 1.8.1 
open-in-browser 0.5.2 
php-ide-serenata 5.2.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
project-manager 3.3.8 
remote-ftp 2.2.4 
w3c-validation 0.4.0 
```

**Comment by martincysiam** [comment]
Fix can be found here: #1374
