### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'F:/React_project\test.js.txt'

### ISSUE THREAD

**Issue by FlipOK** [mgrenier/remote-ftp#1331]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'F:\React_project\test.js.txt'

```
At fs.js:115

Error: ENOENT: no such file or directory, stat 'F:\React_project\test.js.txt'
    at statSync (fs.js:829:3)
    at Object.fs.statSync (ELECTRON_ASAR.js:284:27)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:696:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:153:9
    at final (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:513:11)
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:550:11)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at Parser.emit (events.js:187:15)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
     -1:45.2.0 remote-ftp:create-ftp-config (textarea.xterm-helper-textarea)
     -1:26.6.0 intentions:highlight (input.hidden-input)
     -1:26.4.0 core:paste (input.hidden-input)
     -0:52.1.0 intentions:highlight (input.hidden-input)
     -0:52 core:paste (input.hidden-input)
 10x -0:44.4.0 intentions:highlight (input.hidden-input)
     -0:43.6.0 core:copy (input.hidden-input)
 55x -0:33.1.0 intentions:highlight (input.hidden-input)
     -0:30.8.0 core:save (input.hidden-input)
     -0:19.8.0 remote-ftp:toggle (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-oracle 1.4.4 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.41 
git-plus 8.7.1 
intentions 1.1.5 
language-oracle 1.9.0 
linter 2.3.1 
linter-js-standard 7.0.0 
linter-php 1.6.1 
linter-ui-default 1.8.1 
plsql-linter 2.3.2 
remote-ftp 2.2.4 
terminal-tab 0.6.0 
```

**Comment by martincysiam** [comment]
Fix can be found here: #1374
