### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:/Works\dscontents.com\atom-sftp-sync.j...

### ISSUE THREAD

**Issue by subi9807** [mgrenier/remote-ftp#1335]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Works\dscontents.com\atom-sftp-sync.json'

```
At fs.js:122

Error: ENOENT: no such file or directory, stat 'C:\Works\dscontents.com\atom-sftp-sync.json'
    at statSync (fs.js:876:3)
    at Object.fs.statSync (electron/js2c/asar.js:276:27)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:621:9)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:750:16
    at Object.e (/packages/remote-ftp/lib/connectors/sftp.js:610:22)
    at /packages/remote-ftp/lib/connectors/sftp.js:499:27)
    at WriteStream.emit (events.js:199:15)
    at finishMaybe (_stream_writable.js:646:14)
    at _stream_writable.js:624:5
    at WriteStream._final (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:2971:3)
    at callFinal (_stream_writable.js:617:10)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

### Commands

```
     -0:42.4.0 core:select-all (input.hidden-input)
     -0:42.2.0 core:copy (input.hidden-input)
     -0:40.6.0 core:paste (input.hidden-input)
     -0:39.9.0 core:save (input.hidden-input)
     -0:30 core:move-right (input.hidden-input)
     -0:28.5.0 core:save (input.hidden-input)
     -0:23.9.0 editor:select-to-first-character-of-line (input.hidden-input)
  3x -0:23.3.0 core:select-right (input.hidden-input)
     -0:22.6.0 core:move-right (input.hidden-input)
     -0:21.8.0 core:move-left (input.hidden-input)
     -0:21.4.0 core:select-right (input.hidden-input)
     -0:20.8.0 core:move-right (input.hidden-input)
  7x -0:20.3.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:18.6.0 core:select-left (input.hidden-input)
     -0:18.3.0 core:delete (input.hidden-input)
     -0:17.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
Atom-SFTP-sync 2.0.1 
indent-guide-improved 1.4.13 
jshint 1.8.6 
react 0.18.0 
remote-ftp 2.2.4 
Remote-SSH 0.11.0 
```

**Comment by martincysiam** [comment]
Fix can be found here: #1374
