### ISSUE TITLE
Uncaught Error: Unexpected packet before version

### ISSUE THREAD

**Issue by Andrres017** [mgrenier/remote-ftp#1339]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: Unexpected packet before version

```
At events.js:171

Error: Unexpected packet before version
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:306:27)
    at SFTPStream.Transform._read (_stream_transform.js:187:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:175:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at SFTPStream.Writable.write (_stream_writable.js:299:11)
    at Channel.ondata (_stream_readable.js:706:22)
    at Channel.emit (events.js:194:13)
    at Channel.Readable.read (_stream_readable.js:497:10)
    at flow (_stream_readable.js:970:34)
    at resume_ (_stream_readable.js:951:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

### Commands

```
     -5:09.4.0 remote-ftp:create-sftp-config (ul.list-inline.tab-bar.inset-panel)
     -4:33.6.0 remote-ftp:toggle (atom-pane.pane.active)
     -4:26.5.0 remote-ftp:create-sftp-config (atom-pane.pane.active)
     -4:18.8.0 application:open-folder (div.offline)
     -3:58.7.0 remote-ftp:create-sftp-config (div.tool-panel.tree-view)
  3x -3:11.7.0 core:paste (input.hidden-input)
     -2:46.2.0 core:save (input.hidden-input)
     -0:20.1.0 core:backspace (input.hidden-input)
  2x -0:19.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
remote-ftp 2.2.4 
```

**Comment by Andrres017** [comment]
lo solucione desde el servidor colocando el tlp.
