### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/github\Thaiticketonline\.ftpignore'

### ISSUE THREAD

**Issue by FewZa007** [mgrenier/remote-ftp#1353]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\gafiw\github\Thaiticketonline\.ftpignore'

```
At fs.js:126

Error: ENOENT: no such file or directory, stat 'C:\Users\gafiw\github\Thaiticketonline\.ftpignore'
    at statSync (fs.js:856:3)
    at fs.statSync (electron/js2c/asar.js:276:27)
    at Object.fs.statSync (electron/js2c/asar.js:276:27)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:621:9)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:696:16
    at callCompleted (/packages/remote-ftp/lib/connectors/sftp.js:173:53)
    at oneDirCompleted (/packages/remote-ftp/lib/connectors/sftp.js:177:25)
    at /packages/remote-ftp/lib/connectors/sftp.js:258:36
    at Array.forEach (<anonymous>)
    at /packages/remote-ftp/lib/connectors/sftp.js:193:12
    at /packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:1631:13
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:389:17)
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at SFTPStream.Writable.write (_stream_writable.js:301:11)
    at Channel.ondata (_stream_readable.js:713:22)
    at Channel.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Channel.Readable.push (_stream_readable.js:210:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:200:13)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3191:10)
```

### Commands

```
     -9:28.1.0 core:paste (input.hidden-input)
     -4:29.5.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:25.3.0 core:paste (input.hidden-input)
     -0:24.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
remote-ftp 2.2.4 
```

**Comment by martincysiam** [comment]
Fix can be found here: #1374
