### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/AppData\Local\atom\app-1.53.0\ftpconfig'

### ISSUE THREAD

**Issue by gkhkac230** [mgrenier/remote-ftp#1355]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\klcns\AppData\Local\atom\app-1.53.0\ftpconfig'

```
At fs.js:126

Error: ENOENT: no such file or directory, stat 'C:\Users\klcns\AppData\Local\atom\app-1.53.0\ftpconfig'
    at statSync (fs.js:856:3)
    at fs.statSync (electron/js2c/asar.js:276:27)
    at Object.fs.statSync (electron/js2c/asar.js:276:27)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:621:9)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:696:16
    at callCompleted (/packages/remote-ftp/lib/connectors/sftp.js:173:53)
    at oneDirCompleted (/packages/remote-ftp/lib/connectors/sftp.js:177:25)
    at /packages/remote-ftp/lib/connectors/sftp.js:238:40
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:503:15)
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at SFTPStream.Writable.write (_stream_writable.js:301:11)
    at Channel.ondata (_stream_readable.js:713:22)
    at Channel.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Channel.Readable.push (_stream_readable.js:210:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:200:13)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3191:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:701:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at SSH2Stream.Writable.write (_stream_writable.js:301:11)
    at Socket.ondata (_stream_readable.js:713:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

### Commands

```
     -7:47.8.0 remote-ftp:connect (input.hidden-input)
  3x -7:44.4.0 core:backspace (input.hidden-input)
  2x -7:37 remote-ftp:connect (input.hidden-input)
     -4:36.6.0 tree-view:copy (div.tool-panel.tree-view)
     -3:33.3.0 remote-ssh:start (input.hidden-input)
     -3:22.1.0 remote-ftp:connect (input.hidden-input)
     -1:52.2.0 core:select-all (input.hidden-input)
     -1:51.5.0 core:backspace (input.hidden-input)
     -1:47.6.0 tree-view:remove (span.name.icon.icon-file-text)
     -1:35 remote-ftp:toggle (input.hidden-input)
     -1:03.1.0 core:paste (input.hidden-input)
 12x -0:56.5.0 core:backspace (input.hidden-input)
     -0:41.5.0 core:move-down (input.hidden-input)
  3x -0:41 core:move-right (input.hidden-input)
  7x -0:39.9.0 core:backspace (input.hidden-input)
     -0:20.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
emmet 2.4.3 
ftp-remote-edit 0.18.1 
ftp-remote-edit-plus 1.3.1 
korean-menu 1.35.0 
korean-spellchecker-daum 0.1.6 
remote-ftp 2.2.4 
Remote-SSH 0.11.0 
ssh-config 0.14.0 
```

**Comment by martincysiam** [comment]
Fix can be found here: #1374
