### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Desktop/PHP/PHP dossier/Les bases/base...

### ISSUE THREAD

**Issue by louise-yan44** [mgrenier/remote-ftp#1361]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.6
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/naylemoigne/Desktop/PHP/PHP dossier/Les bases/base.php'

```
At fs.js:126

Error: ENOENT: no such file or directory, stat '/Users/naylemoigne/Desktop/PHP/PHP dossier/Les bases/base.php'
    at statSync (fs.js:856:3)
    at fs.statSync (electron/js2c/asar.js:276:27)
    at Object.fs.statSync (electron/js2c/asar.js:276:27)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:696:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:153:9
    at final (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:515:11)
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:552:11)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at Parser.emit (events.js:205:15)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:295:20)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

### Commands

```
     -2:43.9.0 core:save (input.hidden-input)
     -1:43.3.0 remote-ftp:download-selected (li.file.entry.list-item.selected)
     -0:25.2.0 remote-ftp:copy-name (li.file.entry.list-item.selected)
     -0:19.4.0 tree-view:duplicate (ol.tree-view-root.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:14.4.0 core:copy (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:12.2.0 tree-view:paste (div.tool-panel.tree-view)
```

### Non-Core Packages

```
emmet 2.4.3 
project-manager 3.3.8 
remote-ftp 2.2.4 
tool-bar 1.4.2 
```

**Comment by martincysiam** [comment]
Fix can be found here: #1374
