### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'B:/Documents\GitHub\squadronlabs\server\...

### ISSUE THREAD

**Issue by martincysiam** [mgrenier/remote-ftp#1370]
[Enter steps to reproduce:]

Ensure disconnected due to timeout or loss of connection
Save file without connecting

**Atom**: 1.49.0-beta0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'B:\Documents\GitHub\squadronlabs\server\.htaccess'

```
At fs.js:122

Error: ENOENT: no such file or directory, stat 'B:\Documents\GitHub\squadronlabs\server\.htaccess'
    at statSync (fs.js:876:3)
    at Object.fs.statSync (electron/js2c/asar.js:276:27)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:696:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:153:9
    at final (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:515:11)
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:552:11)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at Parser.emit (events.js:199:15)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:295:20)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:165:17)
```

### Commands

```
  7x -2:51.1.0 core:close (input.hidden-input)
     -0:18.6.0 core:backspace (input.hidden-input)
     -0:18.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:18.3.0 editor:newline (input.hidden-input)
     -0:18.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:18.1.0 editor:newline (input.hidden-input)
     -0:16.8.0 core:backspace (input.hidden-input)
     -0:16.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:16.2.0 editor:newline (input.hidden-input)
     -0:15.5.0 core:move-down (input.hidden-input)
  3x -0:14.7.0 core:move-up (input.hidden-input)
     -0:14.2.0 core:backspace (input.hidden-input)
  3x -0:13.7.0 core:move-down (input.hidden-input)
  3x -0:13.2.0 core:move-up (input.hidden-input)
  2x -0:10.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-debug-ui 1.0.4 
atom-debugger 0.1.6 
atom-ide-ui 0.13.0 
bracket-colorizer 1.4.0 
Breakpoints 0.1.2 
close-tags 0.6.0 
emmet 2.4.3 
file-icons 2.1.47 
grammar-token-limit 0.1.1 
ide-php 0.7.18 
php-debug 0.3.5 
php-fmt 0.1.2 
php-hyperclick 1.2.1 
remote-ftp 2.2.4 
teletype 0.13.4 
termination 0.7.6 
```

**Comment by martincysiam** [comment]
Fix can be found here: https://github.com/icetee/remote-ftp/pull/1374
