### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/OneDrive - Cysiam Ltd/github/app_login...

### ISSUE THREAD

**Issue by martincysiam** [mgrenier/remote-ftp#1373]
[Enter steps to reproduce:]

File is attempting to upload.
Disconnect from FTP
Change FTP credentials (might not be necessary)
Reconnect to FTP
Error

**Atom**: 1.58.0-beta0 x64
**Electron**: 9.4.4
**OS**: macOS 11.4
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/martinnajemi/OneDrive - Cysiam Ltd/github/app_login/app1/login/index.php'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, stat '/Users/martinnajemi/OneDrive - Cysiam Ltd/github/app_login/app1/login/index.php'
    at statSync (fs.js:915:3)
    at Object.fs.statSync (electron/js2c/asar.js:278:27)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:750:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:638:9)
    at /packages/remote-ftp/lib/connectors/ftp.js:665:16
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1090:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at Parser.emit (events.js:228:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:295:20)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```

### Commands

```
     -5:44.9.0 core:close (input.hidden-input)
  2x -5:25.9.0 core:select-up (input.hidden-input)
     -5:25.4.0 core:backspace (input.hidden-input)
     -5:24.9.0 core:save (input.hidden-input)
     -4:58.2.0 remote-ftp:create-ftp-config (div.tool-panel.tree-view)
     -4:54.9.0 datatip:toggle (input.hidden-input)
  3x -4:54.8.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -4:54.2.0 datatip:toggle (input.hidden-input)
  2x -2:54.8.0 core:paste (input.hidden-input)
     -2:50.5.0 core:save (input.hidden-input)
  2x -2:40 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-debug-ui 1.0.4 
atom-debugger 0.1.6 
atom-ide-ui 0.13.0 
bracket-colorizer 1.4.0 
close-tags 0.6.0 
emmet 2.4.3 
file-icons 2.1.47 
grammar-token-limit 0.1.1 
hyperclick-php 0.3.0 
ide-php 0.7.18 
php-debug 0.3.5 
php-fmt 0.1.2 
remote-ftp 2.2.4 
teletype 0.13.4 
```

**Comment by martincysiam** [comment]
Fix can be found here: https://github.com/icetee/remote-ftp/pull/1374
